[package]
edition = "2021"
name = "bevy_sp_tiled"
version = "0.1.0"

authors = ["Steve Pryde <steve@stevepryde.com>"]
description = "Support for Tiled maps in Bevy"
homepage = "https://github.com/stevepryde/bevy_sp"
license = "MIT"
readme = "README.md"
repository = "https://github.com/stevepryde/bevy_sp"

categories = ["game-development"]
keywords = ["bevy", "tiled", "tilemap", "game", "plugin"]

[features]
default = ["render"]
# Expose features of the bevy_ecs_tilemap crate.
atlas = ["bevy_ecs_tilemap/atlas"]
render = ["bevy_ecs_tilemap/render"]
serde = ["bevy_ecs_tilemap/serde"]

# Physics
physics = []
rapier = ["bevy_rapier2d", "physics"]
rapier_debug = ["rapier", "bevy_rapier2d/debug-render-2d"]

# WASM
wasm = ["bevy_rapier2d/wasm-bindgen", "tiled/wasm"]

[dependencies]
bevy = "0.14.0"
bevy_ecs_tilemap = "0.14"
futures-lite = "2.3.0"
log = "0.4"
thiserror = "1.0.62"
tiled = "0.12.0"

# Optional dependencies, enabled via features.
bevy_rapier2d = {version = "0.27.0", optional = true}

[target.'cfg(target_family = "wasm")'.dependencies]
bevy_rapier2d = {version = "0.27.0", features = ["wasm-bindgen"], optional = true}
tiled = {version = "0.12.0", features = ["wasm"]}

[dev-dependencies]
bevy-inspector-egui = "0.25.1"
bevy_rapier2d = {version = "0.27.0", features = ["debug-render-2d"]}
log = "0.4"

[[example]]
name = "finite"

[[example]]
name = "finite_embedded"

[[example]]
name = "infinite"

[[example]]
name = "infinite_embedded"

[[example]]
name = "reload"

[[example]]
name = "finite_rapier"
required-features = ["rapier_debug"]

[[example]]
name = "infinite_rapier"
required-features = ["rapier_debug"]
